### PR TITLE
Make snooze work locally

### LINKED ISSUE #122: Snooze doesn't work properly
Snooze function moves email out of inbox and into snoozed folder for a few seconds and then the email disappears from the snooze folder and doesn't bounce back

### PR DESCRIPTION
**Pull request by nirmit**
This commit attempts to make snooze functions correctly without depending on Nylas ID subscriptions.

Some modifications are credited to @bengotow (thanks for the idea why!).

Fixes #122 and #159

### CODE REVIEW

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx [hunk 1]
```diff
@@ -110,9 +70,36 @@ class SnoozeStore {
...
+    });
+  }
+  
   deactivate() {
     this.unsubscribers.forEach(unsub => unsub())
   }
 }
 
-export default SnoozeStore;
+export default SnoozeStore;
```
Comment (l2dy) [inline packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: Why removing the newline at EOF?

Comment (nirmit) [reply packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: Argh!  My editor settings are to add new line if they are not ending with a terminator, in this case ;

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx [hunk 2]
```diff
@@ -19,6 +19,7 @@ class SnoozeStore {
       AccountStore.listen(this.onAccountsChanged),
       SnoozeActions.snoozeThreads.listen(this.onSnoozeThreads),
     ]
+    setInterval(this.onUnsnoozeThreads, 60000);  // TODO: Do this a better way.
```
Comment (seesemichaelj) [inline packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: this feels clunky. what would the better way be?

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx [hunk 3]
```diff
@@ -74,34 +55,13 @@ class SnoozeStore {
...
-        DatabaseStore.findAll(Message, {threadId: update.threads.map(t => t.id)}).then((messages) => {
-          for (const message of messages) {
-            const header = message.messageIdHeader;
-            const stableId = message.id;
-            Actions.setMetadata(message, this.pluginId,
-              {expiration: snoozeDate, header, stableId, snoozeCategoryId, returnCategoryId})
-          }
-        });
+      _.each(updatedThreads, (update) => {
+        Actions.setMetadata(update, this.pluginId, { expiration: snoozeDate })
```
Comment (seesemichaelj) [inline packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: looks like you remove the snoozeCatgoryId; this seems like it's removing a feature? am i wrong?

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx [hunk 4]
```diff
@@ -110,6 +70,33 @@ class SnoozeStore {
...
+      _.each(categories, function(category) {
+        snoozeCategories.push(category.serverId);
+      });
+      return snoozeCategories;
+    }).then(snoozeCategories => {
+      DatabaseStore.findAll(Thread).where([
+        Thread.attributes.pluginMetadata.contains('thread-snooze'),
+        Thread.attributes.categories.contains(snoozeCategories)
+      ]).then(threads => {
+        if(threads.length < 1) {
```
Comment (seesemichaelj) [inline packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: meh i dont really care that this is here, but wouldnt this be unnecessary? the idea is the for loop would just execute 0 times if there were no threads

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx (hunk 3 above)
Comment (nirmit) [reply packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: Not really.  The snooze feature moves the message from the `inbox` category to the `n1-snoozed` category and back when the expiration time is reached.  The storage of the category ids are not really (re)used.

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx (hunk 4 above)
Comment (nirmit) [reply packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: Yes, you are right.

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx (hunk 2 above)
Comment (nirmit) [reply packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: A better way would be to add a listener to listen to specific events - but it would require a worker to run continuously and emit events when the expiration time comes.  This event emitter/listener can then be used for `send-later` and `send-reminder` as well.

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx (hunk 3 above)
Comment (seesemichaelj) [reply packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: cool. can we change the "n1-snoozed" label? we're FOR SURE not n1 anymore lol. just make it "[NylasMail]/Snoozed" (mailspring has "[Mailspring]/Snoozed")

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx (hunk 4 above)
Comment (seesemichaelj) [reply packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: k no biggie

File: packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx (hunk 3 above)
Comment (nirmit) [reply packages/client-app/internal_packages/thread-snooze/lib/snooze-store.jsx]: `n1-snoozed` is the internal name for Snoozed.  We can definitely change it.  I will look into it (out for two weeks)!

**Comment by nirmit** [comment]
@seesemichaelj @dweremeichik Are you guys planning to merge this one?
