### PR TITLE
Fix url parsing

### LINKED ISSUE #147: Lots of Words Being Processed as URLs
FYI is turned into a link?
image

I'm guessing this is an issue with the new URL regex that went into #145. Can you take a look into this @nirmit? The URL (when copying link address in Nylas) was `http://FYI`

### PR DESCRIPTION
**Pull request by nirmit**
Missing escapes resulted in incorrect regex being generated that caused issue #147. Tested via decaffienated.

Fixes #147 (references #148)

### CODE REVIEW

File: packages/client-app/src/regexp-utils.coffee [hunk 1]
```diff
@@ -39,78 +39,73 @@ RegExpUtils =
...
+          # telephone links
+          'tel:'
+        ')' 
 
         # optionally followed by:
         '('
           # URL components
           # (last character must not be puncation, hence two groups)
           '(?:[\\+~%\\/\\.\\w\\-_@]*[\\+~%\\/\\w\\-_]+)?'
-
```
Comment (seesemichaelj) [inline packages/client-app/src/regexp-utils.coffee]: why was it necessary to remove these comments? are they not useful?

File: packages/client-app/src/regexp-utils.coffee [hunk 2]
```diff
@@ -39,78 +39,73 @@ RegExpUtils =
...
-            '([A-Za-z]{3,9}:(?:\\/\\/))'
 
-            # username:password (optional)
-            '(?:[\\-;:&=\\+\\$,\\w]+@)?'
+            # domain with common tld
+            '(?:(?:[-\\w\\d{1-3}]+\\.)+(?:' + commonTlds.join('|') + '))'
 
-            # one of:
-            '('
-              # domain with any tld
```
Comment (seesemichaelj) [inline packages/client-app/src/regexp-utils.coffee]: in the original regex, there was support for any tld and not just the common ones. i should have caught this in your first PR. why did you remove any tld in favor for only just the common tlds?

Comment (nirmit) [reply packages/client-app/src/regexp-utils.coffee]: The reason I removed it was because `filename.js` would also appear as a valid domain if we keep it free.  Also, if people didn't put spaces after the periods in their sentences, we might incorrectly assume them as URLs.

File: packages/client-app/src/regexp-utils.coffee (hunk 1 above)
Comment (nirmit) [reply packages/client-app/src/regexp-utils.coffee]: Because the whole expression group is looking for URL components.  I can re-add the comments if you think it will be helpful.

Comment (seesemichaelj) [reply packages/client-app/src/regexp-utils.coffee]: Ya,
```
          # optionally followed by: a query string and/or a #location		
          # (last character must not be puncation, hence two groups)
```
was added for a reason, I see no reason for us to remove it if it makes sense. Please don't make a new PR, just add another commit that adds them back

**Comment by seesemichaelj** [comment]
I tested your branch and it seems to work. If you can just add those comments back, I think I'm okay with this
